version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa@@word
    ports:
      - 1433:1433

  dockersqlserver:
    image: ${DOCKER_REGISTRY-}dockersqlserver
    build:
      context: .
      dockerfile: WebApplication/Dockerfile
    depends_on:
      - db